### PR TITLE
Fix crash in LibraryInitializer because readdir() was not in scope.

### PR DESCRIPTION
**Pull request by men8th**
Fix problem in class LibraryInitializer where function readdir() was defined as a static method. Needs to be either defined as a local function, or called with a fully qualified name, ie logger.internal.LibraryInitializer.readdir(). I chose local function.

Tested with helloWorld.m and test_log.m. Now appears to be working correctly.

### CODE REVIEW

**Comment by apjanke** [comment]
Lot of unrelated-looking changes in XML files here! Could that be cleaned up?

**Comment by apjanke** [comment]
Oh, shoot! Good catch. I'm kinda embarrassed that this one snuck out. My only excuse is that this code path is only hit when running under specifically R2020a. I just don't have the time to test on every version.

Fixed in https://github.com/janklab/SLF4M/commit/f80e15c7895ad0aeb5d4b4d647604083910dd800. Sorry for doing a commit myself and not giving you committer credit, but this is bad enough I wanted to get it fixed right away, and wanted do go with a private function instead of a local function.

Sorry for the slow reply here! My Watch settings for this repo weren't set right, so I wasn't getting notifications of new Issues and PRs. I've fixed that, and will see stuff sooner in the future.

**Comment by apjanke** [comment]
This went out in v1.3.1: https://github.com/janklab/SLF4M/releases/tag/v1.3.1

Wasn't planning on rolling a release for this issue because the bug came in after 1.3.0, but it got accidentally picked up by the 1.3.1 I cut to get out documentation about SLF4M's breakage under Matlab R2021b+; see https://github.com/janklab/SLF4M/issues/7.

**Comment by men8th** [comment]
Hi Andrew, glad you've fixed it. Don't worry, I don't need the credit!

Thanks for providing such a great library.

Tim

**Comment by apjanke** [comment]
You're welcome. Thanks for being a user! That's why I do this in the first place.

**Pull request closed without merging**
